#!/usr/bin/env python3
# Copyright 2026 The views-shell Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Compiles style/theme-map.json layer2_pins into a C++ table.

  gen_theme_map.py <theme-map.json> <output .cc>

Writes GetThemePinBindings() (declared in views_shell/style/theme_mixer.h): one
{omarchy_key, ui::<id>, "<id>"} row per colour id, in the file's order. A pin
key may carry a parenthesised note ("on_accent (derived: ...)"); the key is the
text before " (". Every id must be a kColorSys* name. The table names the
enumerators directly, so a name that is not a real ui::ColorId fails the
compile, which is the point: the JSON binding cannot drift from ui/color.
"""

import json
import re
import sys


def main(argv):
  if len(argv) != 3:
    sys.stderr.write(__doc__)
    return 2
  map_path, out_path = argv[1], argv[2]
  with open(map_path, encoding='utf-8') as f:
    pins = json.load(f)['layer2_pins']

  rows = []
  seen = set()
  for raw_key, ids in pins.items():
    if raw_key == 'note':
      continue
    key = raw_key.split(' (', 1)[0]
    if not re.fullmatch(r'[a-z0-9_]+', key):
      sys.stderr.write(f'gen_theme_map: bad Omarchy key {raw_key!r}\n')
      return 1
    if not isinstance(ids, list) or not ids:
      sys.stderr.write(f'gen_theme_map: {key} pins no ids\n')
      return 1
    for color_id in ids:
      if not re.fullmatch(r'kColorSys[A-Za-z0-9]+', color_id):
        sys.stderr.write(f'gen_theme_map: {color_id!r} is not a kColorSys id\n')
        return 1
      if color_id in seen:
        sys.stderr.write(f'gen_theme_map: {color_id} is pinned twice\n')
        return 1
      seen.add(color_id)
      rows.append(f'    {{"{key}", ui::{color_id}, "{color_id}"}},')

  text = '\n'.join([
      '// Generated by views_shell/style/gen_theme_map.py from',
      '// style/theme-map.json. Do not edit.',
      '',
      '#include <array>',
      '',
      '#include "ui/color/color_id.h"',
      '#include "views_shell/style/theme_mixer.h"',
      '',
      'namespace views_shell {',
      '',
      'base::span<const ThemePinBinding> GetThemePinBindings() {',
      f'  static constexpr std::array<ThemePinBinding, {len(rows)}> kBindings = {{{{',
      *rows,
      '  }};',
      '  return kBindings;',
      '}',
      '',
      '}  // namespace views_shell',
      '',
  ])
  with open(out_path, 'w', encoding='utf-8') as f:
    f.write(text)
  return 0


if __name__ == '__main__':
  sys.exit(main(sys.argv))
