// Copyright 2026 The views-shell Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// The theme Tom passes, applied through ui::ColorProvider (rule R17;
// style/tokens/README.md "How it is applied"):
//
//   Layer 1, the seed. ThemeController sets the native theme's preferred colour
//   scheme from the resolved mode and its user colour from chromium.theme or
//   the background, neutralised (theme-map.json layer1_seed). Every widget's
//   ColorProviderKey then carries color_mode, user_color, the native theme's
//   default user_color_source kAccent and no scheme variant, which the stock
//   ref mixer reads as kTonalSpot. Every kColorSys* role the theme does not pin
//   is the stock tonal rendition of that seed.
//
//   Layer 2, the pins. Exactly one ColorMixer, appended last through
//   ui::ColorProviderManager::AppendColorProviderInitializer, sets each
//   kColorSys* id named in style/theme-map.json layer2_pins to the resolved
//   value of its Omarchy key. The binding is compiled in: gen_theme_map.py
//   turns //views_shell/data/style/theme-map.json into a table of real
//   ui::ColorId enumerators, so a name that is not one fails the build.
//
//   Layer 3 (shell.toml sections) is not read yet.
//
// A second Apply() is a live re-apply: the pins are swapped, the colour
// provider cache is reset and the native theme notifies its observers, so every
// view gets OnThemeChanged() without rebuilding a surface.

#ifndef VIEWS_SHELL_STYLE_THEME_MIXER_H_
#define VIEWS_SHELL_STYLE_THEME_MIXER_H_

#include <optional>
#include <string>
#include <utility>
#include <vector>

#include "base/containers/span.h"
#include "base/files/file_path.h"
#include "base/memory/weak_ptr.h"
#include "base/types/expected.h"
#include "base/values.h"
#include "third_party/skia/include/core/SkColor.h"
#include "ui/color/color_id.h"
#include "ui/color/color_provider_key.h"
#include "views_shell/style/theme_directory.h"

namespace ui {
class ColorProvider;
class NativeTheme;
}  // namespace ui

namespace views_shell {

// One row of style/theme-map.json layer2_pins: the resolved Omarchy key whose
// value the id is set to. Generated by gen_theme_map.py.
struct ThemePinBinding {
  const char* omarchy_key;
  ui::ColorId id;
  const char* id_name;
};

// Every pin, in theme-map.json order (generated table).
base::span<const ThemePinBinding> GetThemePinBindings();

// A theme ready to apply: the resolved palette and what it means for colour.
struct ResolvedTheme {
  ResolvedTheme();
  ResolvedTheme(const ResolvedTheme&);
  ResolvedTheme& operator=(const ResolvedTheme&);
  ResolvedTheme(ResolvedTheme&&);
  ResolvedTheme& operator=(ResolvedTheme&&);
  ~ResolvedTheme();

  // Omarchy's resolved palette (omarchy_cascade.h), plus on_accent.
  ThemePalette palette;
  ui::ColorProviderKey::ColorMode color_mode =
      ui::ColorProviderKey::ColorMode::kDark;
  // Layer 1: the neutralised seed.
  SkColor seed = SK_ColorBLACK;
  // Layer 2: every pin whose key resolved to #rrggbb, in table order.
  std::vector<std::pair<ui::ColorId, SkColor>> pins;
};

// theme-map.json layer1_seed: when max+min <= 16, or max >= 250 with
// chroma (max-min) <= 4, the channel average (rounded down) on all three
// channels, so a near-black or near-white seed stays neutral; else unchanged.
SkColor NeutraliseSeed(SkColor color);

// WCAG 2 contrast ratio (sRGB, 0.04045 knee), as tools/theme-goldens.sh
// computes it for on_accent.
double ContrastRatio(SkColor a, SkColor b);

// Resolves `theme`: Omarchy's cascade, on_accent (background when accent
// contrasts with the background at least as much as with bright_foreground,
// else bright_foreground), the mode ("light" is light, anything else dark), the
// seed and the pins.
ResolvedTheme ResolveTheme(const ThemeDirectory& theme);

// LoadThemeDirectory() then ResolveTheme().
base::expected<ResolvedTheme, std::string> LoadAndResolveTheme(
    const base::FilePath& dir);

// The pins as style/tokens/fixtures/<theme>.mixer.json holds them:
// id name -> "#rrggbb".
base::Value::Dict PinsAsDict(const ResolvedTheme& theme);

// Adds the one pin mixer for `theme` to `provider` (layer 2).
void AddThemePinMixer(const ResolvedTheme& theme, ui::ColorProvider* provider);

// Owns the applied theme for the process. Create it once, after the process
// bootstrap and before the first widget; it must outlive every widget.
class ThemeController {
 public:
  ThemeController();
  ThemeController(const ThemeController&) = delete;
  ThemeController& operator=(const ThemeController&) = delete;
  ~ThemeController();

  // Applies `theme` to `native_theme` (layer 1) and to the colour pipeline
  // (layer 2). The first call appends the pin mixer to the global
  // ui::ColorProviderManager; later calls replace the theme it reads, reset the
  // provider cache and notify the native theme's observers (live re-apply).
  void Apply(ResolvedTheme theme, ui::NativeTheme* native_theme);

  const ResolvedTheme* current() const {
    return theme_ ? &*theme_ : nullptr;
  }

 private:
  void AddMixer(ui::ColorProvider* provider, const ui::ColorProviderKey& key);

  std::optional<ResolvedTheme> theme_;
  bool initializer_appended_ = false;
  base::WeakPtrFactory<ThemeController> weak_ptr_factory_{this};
};

}  // namespace views_shell

#endif  // VIEWS_SHELL_STYLE_THEME_MIXER_H_
